// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC73ge9dAdcI-MSLBOqG8HECIsJFhQb0ak',
    appId: '1:578623964983:android:7ed9a100d60d7f49dbfcb2',
    messagingSenderId: '578623964983',
    projectId: 'whagons-5',
    storageBucket: 'whagons-5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg0Ewp4rvarD0pBQq3D19-mydi9oiiZ3g',
    appId: '1:578623964983:ios:a463920fc59dcb35dbfcb2',
    messagingSenderId: '578623964983',
    projectId: 'whagons-5',
    storageBucket: 'whagons-5.firebasestorage.app',
    iosClientId: '578623964983-06ekrieen5u7o6fcj9879oqsobp123mv.apps.googleusercontent.com',
    iosBundleId: 'com.example.whagons5App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg0Ewp4rvarD0pBQq3D19-mydi9oiiZ3g',
    appId: '1:578623964983:ios:a463920fc59dcb35dbfcb2',
    messagingSenderId: '578623964983',
    projectId: 'whagons-5',
    storageBucket: 'whagons-5.firebasestorage.app',
    iosClientId: '578623964983-06ekrieen5u7o6fcj9879oqsobp123mv.apps.googleusercontent.com',
    iosBundleId: 'com.example.whagons5App',
  );
}
